baseURL                   = "https://ErinOrstrom.com"
builddrafts                = false
languageCode               = "en-US"
canonifyurls               = true
contentdir                 = "content"
layoutdir                  = "layouts"
publishdir                 = "public"
enableEmoji                = true
hasCJKLanguage             = true
summaryLength              = 200
Paginate                   = 3

theme                      = "AllinOne"
title                      = "Erin Orstrom"

pygmentsuseclasses         = true


[permalinks]
  blog                     = "blog/:year-:month/:slug/"


[taxonomies]
  tag                      = "tags"
  series                   = "series"
  category                 = "categories"


[menu]
  [[menu.main]]
    name                   = "Blog"
    weight                 = -120
    identifier             = "blog"
    url                    = "blog/"  

  [[menu.main]]
    name                   = "Moment"
    weight                 = -110
    identifier             = "moment"
    url                    = "moment/" 

  [[menu.main]]
    name                   = "About"
    weight                 = -100
    identifier             = "about"
    url                    = "about/"  

 

[params]
  faviconfile              = "img/favicon_io/favicon-32x32.png"               # from static/
  avatar                   = "img/2016_05_19_NSS_Cohort_12_0274_T cropped.jpg"             # path to image in static dir e.g img/avatar.png 
  author                   = "Erin Orstrom"
  description              = ["Technology Professional", "Product Owner. Software Developer. Data Investigator.", "Traveler. Video Gamer. Avid Reader. Life-long Learner."]           # appears in the site header when set to a non-empty string
  welcome_head             = "Welcome!"
  welcome_word             = "Glad you stopped by for a visit."

  latestpostscount         = 5                             # how many posts to display on the home page
  bloggroupby              = 'month'
  dateform                 = "Jan 2, 2006"
  dateformfull             = "2006-01-02  Monday  15:04:05"
  noshowreadtime           = false                         # if true, don't show "<x> minutes read" in posts

  custom_css               = ["css/form.css", "css/custom.css"]

  # slides
  slidesDirPath            = "themes/AllinOne/static/img/header-slides"    # path to image in local dir (path for hugo)
  slidesDirPathURL         = "img/header-slides"    # path to image in static dir (for static pages)

  # highlighting 
  highlightjs              = true

  # latex
  katex                    = true

  # links
  email                    = "eorstrom@gmail.com"
  github                   = "https://github.com/eorstrom"
  linkedin                 = "https://www.linkedin.com/in/erinorstrom/"
  facebook                 = false
  twitter                  = "https://twitter.com/eeyorestrom" 
  px500                    = false
  instagram                = "https://www.instagram.com/eeyorestrom/"
  include_rss              = false                          # include RSS <link> tag in <head> and show RSS icon
  
  # analytics
  googleAnalytics          = "UA-81706954-1"